### PR TITLE
Keep allow_hidden on contents managers created by wrapping extensions

### PR DESCRIPTION
**Pull request by trungminhdo4-glitch**
HUMAN: (Owner-authorized; posted by my agent on my behalf.)

Draft opened with AI assistance; all findings below were verified by live
reproduction on 2026-08-21.

## Context

The original `require_hash` failure reported in #113
(`JupytextContentsManager.get() got an unexpected keyword argument 'require_hash'`)
was a Jupytext compatibility gap with jupyter_server >= 2.11 and is already
fixed upstream (Jupytext 1.16.5, 2024-12-15). That part requires no Pretzel
change.

A separate regression from the same issue is still reproducible on a fresh
install (`pip install pretzelai jupytext`):

- Pretzel's `LabApp.initialize()` sets `contents_manager.allow_hidden = True`
  imperatively so its AI chat can store state under the hidden `.pretzel/`
  directory.
- Server extensions load after `LabApp.initialize()`. Jupytext's extension then
  replaces the contents manager with a fresh instance
  (`app.contents_manager = app.contents_manager_class(parent=app, log=app.log)`),
  which defaults to `allow_hidden = False`.
- All `.pretzel/*` GET/PUT requests are then refused (404/400), so chat history
  and embedding storage silently breaks whenever Jupytext is installed — with
  or without the `require_hash` fix.

## Fix

In addition to the existing imperative assignment, `LabApp.initialize()` now
also writes `serverapp.config.ContentsManager.allow_hidden = True`. Traitlets
applies parent config at instantiation time, so any contents manager created
afterwards — including Jupytext's replacement — inherits the setting. The
imperative line is kept for the manager instance already in use.

## Reproduction (Python 3.12.6, Windows, `pretzel-lab` + `/api/contents`)

| Environment | `.pretzel` PUT (dir/file) | `.pretzel` GET | Result |
|---|---|---|---|
| pretzelai 4.2.11 + jupyter_server 2.20.0, no Jupytext | 201 / 201 | 200 | pass (baseline) |
| + Jupytext 1.19.5 (current) | 400 / 400 | 404 | fails — this PR's regression |
| + Jupytext 1.19.5 + this fix | 201 / 201 | 200 | pass |
| pretzelai 4.2.11 + jupyter_server 2.14.1 + Jupytext 1.16.4 + this fix | 201 / 201 | 200 | pass (historical issue-time stack) |

## Tests

- New regression test
  `test_allow_hidden_survives_contents_manager_replacement` in
  `jupyterlab/tests/test_app.py`: fails before the fix (replacement manager has
  `allow_hidden=False`), passes after.
- Focused test run: 1 passed. Adjacent
  `test_jupyterlab.py::test_load_extension`: passed. Ruff clean on touched
  files. `git diff --check` clean.

This PR does not address the historical `require_hash` TypeError — that is
resolved upstream — and only targets the remaining `.pretzel` storage
regression.

Related: #113

### CODE REVIEW

**Comment by trungminhdo4-glitch** [comment]
Hello — friendly ping on this one: it is mergeable and CI was green at last check. Happy to rebase or adjust if you would like anything changed.
